definitions:
  controller.CommentActionResponse:
    properties:
      comment:
        $ref: '#/definitions/model.Comment'
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  controller.CommentListResponse:
    properties:
      comment_list:
        items:
          $ref: '#/definitions/model.Comment'
        type: array
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  controller.FavoriteActionResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  controller.FavoriteListResponse:
    properties:
      response:
        $ref: '#/definitions/model.Response'
      video_list:
        items:
          $ref: '#/definitions/model.Video'
        type: array
    type: object
  controller.FeedResponse:
    properties:
      next_time:
        type: integer
      status_code:
        type: integer
      status_msg:
        type: string
      video_list:
        items:
          $ref: '#/definitions/model.Video'
        type: array
    type: object
  controller.UserLoginResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      token:
        type: string
      user_id:
        type: integer
    type: object
  controller.UserinfoResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user:
        $ref: '#/definitions/model.UserInfo'
    type: object
  controller.VideoListResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      video_list:
        items:
          $ref: '#/definitions/model.Video'
        type: array
    type: object
  model.Comment:
    properties:
      content:
        type: string
      create_date:
        type: string
      id:
        type: integer
      user:
        allOf:
        - $ref: '#/definitions/model.UserInfo'
        description: 评论用户作者的相关信息
    type: object
  model.Response:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  model.UserInfo:
    properties:
      avatar:
        description: 用户头像
        type: string
      background_image:
        description: 用户背景
        type: string
      favorite_count:
        type: integer
      follow_count:
        type: integer
      follower_count:
        type: integer
      id:
        type: integer
      is_follow:
        type: boolean
      name:
        type: string
      total_favorited:
        type: string
      work_count:
        description: 用户作品数量
        type: integer
    type: object
  model.Video:
    properties:
      author:
        allOf:
        - $ref: '#/definitions/model.UserInfo'
        description: 视频作者的相关信息
      comment_count:
        type: integer
      cover_url:
        type: string
      favorite_count:
        type: integer
      id:
        type: integer
      is_favorite:
        type: boolean
      play_url:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /douyin/comment/action/:
    post:
      consumes:
      - application/json
      description: 已经登录的用户在视频下方进行评论
      parameters:
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: string
      - description: 1-发布评论 2-删除评论
        in: query
        name: action_type
        required: true
        type: string
      - description: 用户填写的评论内容，在action_type=1的时候使用
        in: query
        name: comment_text
        type: string
      - description: 要删除的评论id，在action_type=2的时候使用
        in: query
        name: comment_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CommentActionResponse'
      summary: 登录用户对视频进行评论
      tags:
      - 互动接口
  /douyin/comment/list/:
    get:
      consumes:
      - application/json
      description: 查看视频的所有评论，按发布时间倒序,并不需要限制用户的登录状态吧
      parameters:
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CommentListResponse'
      summary: 查看视频的所有评论，按发布时间倒序
      tags:
      - 互动接口
  /douyin/favorite/action/:
    post:
      consumes:
      - application/json
      description: 用户点赞功能，当用户点赞时小红心会点亮，作品点赞数量会+1,点赞列表会多一条记录，取消点赞则反之
      parameters:
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      - description: 点赞标志 1-点赞 2-取消点赞
        in: query
        name: action_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FavoriteActionResponse'
      summary: 用户点赞
      tags:
      - 互动接口
  /douyin/favorite/list/:
    get:
      consumes:
      - application/json
      description: 查看用户的所有点赞视频
      parameters:
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FavoriteListResponse'
      summary: 用户喜欢列表
      tags:
      - 互动接口
  /douyin/feed/:
    get:
      consumes:
      - application/json
      description: 不限制登录状态，返回按投稿时间倒序的视频列表，视频数由服务端控制，单次最多30个
      parameters:
      - description: 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
        in: query
        name: latest_time
        type: string
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FeedResponse'
      summary: 视频流接口，主页的视频流
      tags:
      - 视频接口
  /douyin/publish/action/:
    post:
      consumes:
      - multipart/form-data
      description: 投稿首先得鉴权，其次获取用户的上传视频，自动获取封面，上传到云存储，并添加到数据库中
      parameters:
      - description: 视频数据
        in: formData
        name: data
        required: true
        type: file
      - description: 用户鉴权token
        in: formData
        name: token
        required: true
        type: string
      - description: 视频标题
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户投稿
      tags:
      - 视频接口
  /douyin/publish/list/:
    get:
      consumes:
      - application/json
      description: 首先得鉴权，判断token和user_id是否同一个，是否伪造token，其次返回该用户的数据
      parameters:
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      - description: 用户的id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.VideoListResponse'
      summary: 查看用户所有投稿的视频
      tags:
      - 视频接口
  /douyin/user/:
    get:
      consumes:
      - application/json
      description: 获取用户的 id、昵称，如果实现社交部分的功能，还会返回关注数和粉丝数
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserinfoResponse'
      summary: 获取用户的基本信息
      tags:
      - 用户接口
  /douyin/user/login/:
    post:
      consumes:
      - application/json
      description: 用户登录功能，判断密码是否正确
      parameters:
      - description: 账号
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserLoginResponse'
      summary: 用户登录
      tags:
      - 用户接口
  /douyin/user/register/:
    post:
      consumes:
      - application/json
      description: 用户注册，需要判断用户名是否已经被注册了，以及用户密码是否规范
      parameters:
      - description: 账号
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UserLoginResponse'
      summary: 用户注册
      tags:
      - 用户
swagger: "2.0"
